@baseUrl = http://localhost:8000/api/v1

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{"FName": "SHEKHAR",
   "LName": "MEHLA",
    "phone": "0423745",
    "email":"smehla147@gmail.com",
    "password":"123"}
    
###
POST {{baseUrl}}/auth/activate-user
Content-Type: application/json

{ 
  "_id":"677b1fc28fbdaa27879d574e",
  "token":
"1c9a9895-e3e4-4a93-971f-aee2dc45e707"
   }
 

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{"email":"smehla147@gmail.com","password":"123"}

###
GET {{baseUrl}}/auth/renew-accessJwt
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNtZWhsYTE0N0BnbWFpbC5jb20iLCJpYXQiOjE3Mzc1MDIzNzAsImV4cCI6MTc0MDA5NDM3MH0.dYvI58cOPX_95X6iD4qj2unq4Kx9AgGmikqhkZQ0Cd4
    

    


###
GET  {{baseUrl}}/user/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNtZWhsYTE0N0BnbWFpbC5jb20iLCJpYXQiOjE3Mzc0MDMxMDQsImV4cCI6MTczNzQwNDAwNH0.JuWt0Ir702uGH_GXGeAjcsKQrfwAHXsV6aKdeEvM9Mg
    



 