@baseUrl = http://localhost:8000/api/v1

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{"FName": "Punith",
   "LName": "Bajaj",
    "phone": "0423745",
    "email":"smehla147@gmail.com",
    "password":"123"}
    
###
POST {{baseUrl}}/auth/activate-user
Content-Type: application/json

{ 
  "_id":"677b1fc28fbdaa27879d574e",
  "token":
"1c9a9895-e3e4-4a93-971f-aee2dc45e707"
   }
 

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{"email":"smehla147@gmail.com","password":"123"}
    



 