const booksData = [
  {
    title: "The Great Adventure",
    status: "inActive",
    slug: "the-great-adventure",
    author: "John Doe",
    isbn: 9781234567890,
    publishedDate: new Date('2021-01-01'),
    smallDescription: "A thrilling tale of adventure and discovery.",
    description: "Join the characters in an epic adventure across the globe.",
    imageUrl: "https://example.com/image1.jpg",
    imageList: ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d4" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d4" },
    genre: "Adventure",
    stockQuantity: 10,
    updatedBy: "60d5f73a4f1c4b1b88c6f8d4"
  },
  {
    title: "Mystery in the Shadows",
    status: "inActive",
    slug: "mystery-in-the-shadows",
    author: "Jane Smith",
    isbn: 9781234567891,
    publishedDate: new Date('2020-05-15'),
    smallDescription: "A suspenseful mystery that keeps you on the edge of your seat.",
    description: "Solve the mystery alongside the protagonist as they uncover dark secrets.",
    imageUrl: "https://example.com/image3.jpg",
    imageList: ["https://example.com/image3.jpg", "https://example.com/image4.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d5" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d5" },
    genre: "Mystery",
    stockQuantity: 5,
    updatedBy: "60d5f73a4f1c4b1b88c6f8d5"
  },
  {
    title: "The Science of Nature",
    status: "inActive",
    slug: "the-science-of-nature",
    author: "Dr. Alice Green",
    isbn: 9781234567892,
    publishedDate: new Date('2018-03-22'),
    smallDescription: "A deep dive into the world of natural science.",
    description: "Explore the wonders of nature and the science that explains it.",
    imageUrl: "https://example.com/image5.jpg",
    imageList: ["https://example.com/image5.jpg", "https://example.com/image6.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d6" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d6" },
    genre: "Science",
    stockQuantity: 20,
    updatedBy: "60d5f73a4f1c4b1b88c6f8d6"
  },
  {
    title: "Cooking for Beginners",
    status: "inActive",
    slug: "cooking-for-beginners",
    author: "Tom Cook",
    isbn: 9781234567893,
    publishedDate: new Date('2019-07-10'),
    smallDescription: "A beginner’s guide to cooking simple and delicious meals.",
    description: "Learn the basics of cooking and enjoy easy-to-follow recipes.",
    imageUrl: "https://example.com/image7.jpg",
    imageList: ["https://example.com/image7.jpg", "https://example.com/image8.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d7" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d7" },
    genre: "Cookbook",
    stockQuantity: 15,
    updatedBy: "60d5f73a4f1c4b1b88c6f8d7"
  },
  {
    title: "Digital Marketing 101",
    status: "inActive",
    slug: "digital-marketing-101",
    author: "Sarah Lee",
    isbn: 9781234567894,
    publishedDate: new Date('2021-11-01'),
    smallDescription: "An introductory guide to digital marketing strategies.",
    description: "Discover the fundamentals of digital marketing and how to grow your business.",
    imageUrl: "https://example.com/image9.jpg",
    imageList: ["https://example.com/image9.jpg", "https://example.com/image10.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d8" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d8" },
    genre: "Business",
    stockQuantity: 25,
    updatedBy: "60d5f73a4f1c4b1b88c6f8d8"
  },
  {
    title: "History of the World",
    status: "inActive",
    slug: "history-of-the-world",
    author: "Mark T. History",
    isbn: 9781234567895,
    publishedDate: new Date('2017-09-14'),
    smallDescription: "A comprehensive guide to the history of the world.",
    description: "Dive into the past and understand the key moments in world history.",
    imageUrl: "https://example.com/image11.jpg",
    imageList: ["https://example.com/image11.jpg", "https://example.com/image12.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d9" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8d9" },
    genre: "History",
    stockQuantity: 8,
    updatedBy: "60d5f73a4f1c4b1b88c6f8d9"
  },
  {
    title: "The Art of Painting",
    status: "inActive",
    slug: "the-art-of-painting",
    author: "Leonardo Da Vinci",
    isbn: 9781234567896,
    publishedDate: new Date('2015-02-20'),
    smallDescription: "Learn the fundamentals of painting from a master.",
    description: "Explore techniques and styles that have shaped the art world.",
    imageUrl: "https://example.com/image13.jpg",
    imageList: ["https://example.com/image13.jpg", "https://example.com/image14.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8da" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8da" },
    genre: "Art",
    stockQuantity: 30,
    updatedBy: "60d5f73a4f1c4b1b88c6f8da"
  },
  {
    title: "The Secret Life of Plants",
    status: "inActive",
    slug: "the-secret-life-of-plants",
    author: "Emily Rose",
    isbn: 9781234567897,
    publishedDate: new Date('2022-06-10'),
    smallDescription: "An exploration into the fascinating world of plants.",
    description: "Understand the importance and mysteries behind plant life.",
    imageUrl: "https://example.com/image15.jpg",
    imageList: ["https://example.com/image15.jpg", "https://example.com/image16.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8db" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8db" },
    genre: "Nature",
    stockQuantity: 50,
    updatedBy: "60d5f73a4f1c4b1b88c6f8db"
  },
  {
    title: "Underwater Wonders",
    status: "inActive",
    slug: "underwater-wonders",
    author: "David Waters",
    isbn: 9781234567898,
    publishedDate: new Date('2019-08-25'),
    smallDescription: "Discover the wonders of underwater ecosystems.",
    description: "Explore the diverse marine life and habitats beneath the sea.",
    imageUrl: "https://example.com/image17.jpg",
    imageList: ["https://example.com/image17.jpg", "https://example.com/image18.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8dc" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8dc" },
    genre: "Nature",
    stockQuantity: 12,
    updatedBy: "60d5f73a4f1c4b1b88c6f8dc"
  },
  {
    title: "Space Exploration",
    status: "inActive",
    slug: "space-exploration",
    author: "Neil Armstrong",
    isbn: 9781234567899,
    publishedDate: new Date('2020-12-01'),
    smallDescription: "The history and future of space exploration.",
    description: "A journey through humanity’s quest to explore outer space.",
    imageUrl: "https://example.com/image19.jpg",
    imageList: ["https://example.com/image19.jpg", "https://example.com/image20.jpg"],
    createdBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8dd" },
    lastUpdatedBy: { name: "Admin", adminId: "60d5f73a4f1c4b1b88c6f8dd" },
    genre: "Science",
    stockQuantity: 17,
    updatedBy: "60d5f73a4f1c4b1b88c6f8dd"
  }
  // Add additional books with similar structure to complete 20 entries.
];


export default booksData;
