const booksData = [
  {
    title: "The Great Adventure",
    status: "active",
    Carousel: "Yes",
    slug: "the-great-adventure",
    author: "John Doe",
    isbn: 9780345391803,
    publishedDate: "2021-05-15T00:00:00Z",
    smallDescription: "A thrilling journey through time and space.",
    description:
      "The Great Adventure tells the story of a time-traveling explorer on a quest to save humanity from an impending apocalypse.",
    imageUrl: "https://example.com/great-adventure.jpg",
    imageList: [
      "https://example.com/great-adventure-1.jpg",
      "https://example.com/great-adventure-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Sci-Fi",
    stockQuantity: 15,
    updatedBy: null,
  },
  {
    title: "The Silent Echo",
    status: "active",
    Carousel: "No",
    slug: "the-silent-echo",
    author: "Jane Smith",
    isbn: 9780452284232,
    publishedDate: "2019-10-23T00:00:00Z",
    smallDescription:
      "A haunting mystery set in the heart of an abandoned mansion.",
    description:
      "The Silent Echo is a spine-chilling thriller about a group of people trapped in an eerie mansion, where each of them must confront their deepest fears.",
    imageUrl: "https://example.com/silent-echo.jpg",
    imageList: [
      "https://example.com/silent-echo-1.jpg",
      "https://example.com/silent-echo-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Horror",
    stockQuantity: 25,
    updatedBy: null,
  },
  {
    title: "Whispers of the Sea",
    status: "inActive",
    Carousel: "Yes",
    slug: "whispers-of-the-sea",
    author: "Mark Thompson",
    isbn: 9780765326995,
    publishedDate: "2017-02-10T00:00:00Z",
    smallDescription:
      "A romance set against the backdrop of a quiet coastal town.",
    description:
      "Whispers of the Sea follows the love story of two souls who meet during a summer vacation in a small coastal town, but their romance is interrupted by a mystery lurking beneath the waves.",
    imageUrl: "https://example.com/whispers-of-the-sea.jpg",
    imageList: [
      "https://example.com/whispers-of-the-sea-1.jpg",
      "https://example.com/whispers-of-the-sea-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Romance",
    stockQuantity: 10,
    updatedBy: null,
  },
  {
    title: "Beyond the Horizon",
    status: "active",
    Carousel: "No",
    slug: "beyond-the-horizon",
    author: "Emily Clark",
    isbn: 9781524737124,
    publishedDate: "2023-01-25T00:00:00Z",
    smallDescription: "An adventure that takes you to the edge of the world.",
    description:
      "Beyond the Horizon is an epic adventure that chronicles the journey of a group of explorers seeking a lost civilization in the vast unexplored jungles of South America.",
    imageUrl: "https://example.com/beyond-the-horizon.jpg",
    imageList: [
      "https://example.com/beyond-the-horizon-1.jpg",
      "https://example.com/beyond-the-horizon-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Adventure",
    stockQuantity: 40,
    updatedBy: null,
  },
  {
    title: "Fallen Leaves",
    status: "inActive",
    Carousel: "Yes",
    slug: "fallen-leaves",
    author: "David Johnson",
    isbn: 9780735210626,
    publishedDate: "2015-06-05T00:00:00Z",
    smallDescription: "A gripping story about loss, redemption, and hope.",
    description:
      "Fallen Leaves is the emotional tale of a family dealing with the aftermath of a devastating loss, and how they come to terms with their grief while finding a path toward healing.",
    imageUrl: "https://example.com/fallen-leaves.jpg",
    imageList: [
      "https://example.com/fallen-leaves-1.jpg",
      "https://example.com/fallen-leaves-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Drama",
    stockQuantity: 5,
    updatedBy: null,
  },
  {
    title: "Mystery of the Red Mask",
    status: "active",
    Carousel: "No",
    slug: "mystery-of-the-red-mask",
    author: "Oliver Harris",
    isbn: 9780439139601,
    publishedDate: "2020-08-13T00:00:00Z",
    smallDescription: "A classic detective story with a modern twist.",
    description:
      "Mystery of the Red Mask is a thrilling detective novel that follows a young investigator trying to solve a series of puzzling crimes that are all connected by a mysterious red mask.",
    imageUrl: "https://example.com/mystery-of-the-red-mask.jpg",
    imageList: [
      "https://example.com/mystery-of-the-red-mask-1.jpg",
      "https://example.com/mystery-of-the-red-mask-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Mystery",
    stockQuantity: 50,
    updatedBy: null,
  },
  {
    title: "The Artist's Journey",
    status: "active",
    Carousel: "Yes",
    slug: "the-artists-journey",
    author: "Samantha Lee",
    isbn: 9781416593112,
    publishedDate: "2022-11-02T00:00:00Z",
    smallDescription:
      "An inspiring tale of an artist's search for meaning and purpose.",
    description:
      "The Artist's Journey is a memoir of an artist's life, capturing her creative struggles and triumphs while seeking her true artistic voice in the midst of a fast-paced world.",
    imageUrl: "https://example.com/artists-journey.jpg",
    imageList: [
      "https://example.com/artists-journey-1.jpg",
      "https://example.com/artists-journey-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Biography",
    stockQuantity: 35,
    updatedBy: null,
  },
  {
    title: "Into the Wild",
    status: "active",
    Carousel: "No",
    slug: "into-the-wild",
    author: "Chris Morrow",
    isbn: 9780385486804,
    publishedDate: "2019-12-01T00:00:00Z",
    smallDescription: "A memoir of a man’s survival in the wild.",
    description:
      "Into the Wild chronicles the life of a man who decided to leave behind civilization and live alone in the wild, learning profound lessons about life and survival.",
    imageUrl: "https://example.com/into-the-wild.jpg",
    imageList: [
      "https://example.com/into-the-wild-1.jpg",
      "https://example.com/into-the-wild-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Non-Fiction",
    stockQuantity: 60,
    updatedBy: null,
  },
  {
    title: "The Enchanted Forest",
    status: "inActive",
    Carousel: "Yes",
    slug: "the-enchanted-forest",
    author: "Rebecca Adams",
    isbn: 9781608194228,
    publishedDate: "2021-04-15T00:00:00Z",
    smallDescription: "A magical adventure for children of all ages.",
    description:
      "The Enchanted Forest is a whimsical tale that follows a group of children who discover a hidden forest filled with fantastical creatures and magic.",
    imageUrl: "https://example.com/enchanted-forest.jpg",
    imageList: [
      "https://example.com/enchanted-forest-1.jpg",
      "https://example.com/enchanted-forest-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Children's Fiction",
    stockQuantity: 70,
    updatedBy: null,
  },
  {
    title: "The Last Kingdom",
    status: "active",
    Carousel: "No",
    slug: "the-last-kingdom",
    author: "Alexander King",
    isbn: 9780452295267,
    publishedDate: "2018-11-02T00:00:00Z",
    smallDescription: "A historical epic of war and power.",
    description:
      "Set in the medieval ages, The Last Kingdom follows the rise and fall of kings as a kingdom faces constant battles for control and power.",
    imageUrl: "https://example.com/last-kingdom.jpg",
    imageList: [
      "https://example.com/last-kingdom-1.jpg",
      "https://example.com/last-kingdom-2.jpg",
    ],
    createdBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    lastUpdatedBy: { name: "Admin User", adminId: "606c72ef1f1c4d32c8c06d59" },
    genre: "Historical Fiction",
    stockQuantity: 80,
    updatedBy: null,
  },
];
export default booksData;
